package com.test.lsm.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.test.lsm.db.bean.PushMsg;

import com.test.lsm.db.PushMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pushMsgDaoConfig;

    private final PushMsgDao pushMsgDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pushMsgDaoConfig = daoConfigMap.get(PushMsgDao.class).clone();
        pushMsgDaoConfig.initIdentityScope(type);

        pushMsgDao = new PushMsgDao(pushMsgDaoConfig, this);

        registerDao(PushMsg.class, pushMsgDao);
    }
    
    public void clear() {
        pushMsgDaoConfig.clearIdentityScope();
    }

    public PushMsgDao getPushMsgDao() {
        return pushMsgDao;
    }

}
